[Settings]
; =========================
; 全局功能开关 / Global Switches
; =========================

# 开启更新，用于控制是否更新接口，若关闭则所有工作模式（获取接口和测速）均停止；可选值: True, False | Enable update, used to control whether to update the interface, if closed, all working modes (get interface and speed measurement) will stop; Optional values: True, False
open_update = True
# 开启无结果频道分类，自动归类至底部；可选值: True, False | Enable empty category, automatically classified to the bottom; Optional values: True, False
open_empty_category = False
# 开启显示更新时间；可选值: True, False | Enable display update time; Optional values: True, False
open_update_time = True
# 开启显示接口说明信息，用于控制是否显示接口来源、分辨率、协议类型等信息，为 $ 符号后的内容，播放软件使用该信息对接口进行描述，若部分播放器（如 PotPlayer）不支持解析导致无法播放可关闭；可选值: True, False | Enable to display interface description information, used to control whether to display interface source, resolution, protocol type and other information, the content after the $ symbol, the playback software uses this information to describe the interface, if some players (such as PotPlayer) do not support parsing and cannot play, you can turn it off; Optional values: True, False
open_url_info = False
# 开启 EPG 功能，支持频道显示预告内容；可选值: True, False | Enable EPG function, support channel display preview content; Optional values: True, False
open_epg = True
# 开启转换生成 m3u 文件类型结果链接，支持显示频道图标；可选值: True, False | Enable to convert and generate m3u file type result links, support display channel icons; Optional values: True, False
open_m3u_result = True
# 单个频道接口数量 | Number of interfaces per channel
urls_limit = 5
# 更新时间显示位置，需要开启 open_update_time 才能生效；可选值: top、bottom；top: 显示于结果顶部，bottom: 显示于结果底部 | Update time display position, need to enable open_update_time to take effect; Optional values: top, bottom; top: display at the top of the result, bottom: display at the bottom of the result
update_time_position = top
# 系统语言设置；可选值: zh_CN、en | Application language setting; Optional values: zh_CN, en
language = zh_CN
